version: '3'

services:
  web:
    build: .
    # Flask app internal port, no need to expose it since Nginx will handle incoming traffic
    # ports:
    #   - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ["./entrypoint.sh"]

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx config
    depends_on:
      - web

volumes:
  mysql-data:
